### ISSUE TITLE
remove panics from `d2mpq.decompressMulti`

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#1018]
in `d2common/d2fileformats/d2mpq/mpq_stream.go`, function `decompressMulti`

panics should instead bubble up errors to be handled gracefully

This is currently crashing the game if you walk outside of town.

**Comment by gravestench** [comment]
This can wait until @Intyre finishes up his MPQ encoder work. After that is finished, this should become high-priority again.

**Comment by ianling** [comment]
This was done as part of #1020
