### ISSUE TITLE
Running on Pi4/Retropie

### ISSUE THREAD

**Issue by Exarkuniv** [OpenDiablo2/OpenDiablo2#1101]
i came across this and thought that i would give it a try. 
i was able to install it with no errors, that i know of. Never used Golang before

so my questions is 
1 can/will this run in command line, Retropie does not have a desktop, but we can use X11

2 and how do you start it. 
i look around and cant find how to start. 
im sure im just missing it 

thanks for any help

**Comment by Exarkuniv** [comment]
messing around with this a little more and this is what i get

pi@retropie:~/OpenDiablo2 $ ./build.sh
OpenDiablo 2 Build Script 0.0.8
Check Go
Install libraries
libraries is installed
Build OpenDiablo 2
build github.com/OpenDiablo2/OpenDiablo2: cannot find module for path io/fs
build github.com/OpenDiablo2/OpenDiablo2: cannot find module for path io/fs
Build finished. Running OpenDiablo2 will generate a config.json file.
If there are subsequent errors, please inspect and edit the config.json file. See doc/index.html for more details
pi@retropie:~/OpenDiablo2 $

i think this just might not work for my system

**Comment by gucio321** [comment]
>build github.com/OpenDiablo2/OpenDiablo2: cannot find module for path io/fs
build github.com/OpenDiablo2/OpenDiablo2: cannot find module for path io/fs

you need to upgade to go 1.16.

**Comment by Exarkuniv** [comment]
@gucio321 thats what i thought, but when i ran `` sudo apt-get install golang``
it tells me that im running  2.11, or im i doing it wrong?

**Comment by gucio321** [comment]
maybe try to download manually:
```sh
wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz
```
and then add to PATH e.g. `export PATH="$PATH:/usr/local/go/bin"

**Comment by Exarkuniv** [comment]
> and then add to PATH e.g. `export PATH="$PATH:/usr/local/go/bin`

for that part i put that in the `.profile`

sorry kinda new on golang

**Comment by Exarkuniv** [comment]
think i might got it

**Comment by Exarkuniv** [comment]
well i got a different error now

pi@retropie:~ $ go get github.com/OpenDiablo2/OpenDiablo2
go: downloading golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4
go: downloading golang.org/x/mobile v0.0.0-20200801112145-973feb4309de
go: downloading golang.org/x/exp v0.0.0-20201008143054-e3b2a7f2fdc7
# runtime
/usr/local/go/src/runtime/mgclarge.go:320:6: s.scavenged undefined (type *mspan                             has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:323:6: s.hugePages undefined (type *mspan                             has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:390:13: s.hugePages undefined (type *mspan                             has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:391:16: s.scavenged undefined (type *mspan                             has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:396:9: mheap_.free undefined (type mheap h                            as no field or method free)
/usr/local/go/src/runtime/mgclarge.go:398:7: s.scavenged undefined (type *mspan                             has no field or method scavenged)
/usr/local/go/src/runtime/signal_unix.go:517:5: crashing redeclared in this bloc                            k
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:1                            5:5
/usr/local/go/src/runtime/signal_unix.go:522:5: testSigtrap redeclared in this b                            lock
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:2                            0:5
/usr/local/go/src/runtime/signal_unix.go:536:6: sighandler redeclared in this bl                            ock
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:3                            3:69
/usr/local/go/src/runtime/stubs32.go:14:6: call16 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/stubs.go:287:55
/usr/local/go/src/runtime/mgclarge.go:398:7: too many errors

**Comment by gravestench** [comment]
please show the output of `go --version`

also, you should be able to just do the following:
```bash
git clone http://github.com/OpenDiablo2/OpenDiablo2
cd OpenDiablo2
go get -d
```

to run from command line, I believe you can prefix your command like this:
```bash
# force using the main display of the system
DISPLAY=:0 go run .
```

**Comment by Exarkuniv** [comment]
go version go1.16.2 linux/arm

**Comment by Exarkuniv** [comment]
when i run go build .

i get this 
pi@retropie:~/OpenDiablo2 $ go build .
runtime
/usr/local/go/src/runtime/mgclarge.go:320:6: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:323:6: s.hugePages undefined (type *mspan has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:390:13: s.hugePages undefined (type *mspan has no field or method hugePages)
/usr/local/go/src/runtime/mgclarge.go:391:16: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/mgclarge.go:396:9: mheap_.free undefined (type mheap has no field or method free)
/usr/local/go/src/runtime/mgclarge.go:398:7: s.scavenged undefined (type *mspan has no field or method scavenged)
/usr/local/go/src/runtime/signal_unix.go:517:5: crashing redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:15:5
/usr/local/go/src/runtime/signal_unix.go:522:5: testSigtrap redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:20:5
/usr/local/go/src/runtime/signal_unix.go:536:6: sighandler redeclared in this block
        previous declaration at /usr/local/go/src/runtime/signal_sighandler.go:33:69
/usr/local/go/src/runtime/stubs32.go:14:6: call16 redeclared in this block
        previous declaration at /usr/local/go/src/runtime/stubs.go:287:55
/usr/local/go/src/runtime/mgclarge.go:398:7: too many errors

**Comment by gravestench** [comment]
what happens if you try to compile like this:
```bash
env GOOS=linux GOARCH=arm GOARM=5 go build .

**Comment by Exarkuniv** [comment]
pi@retropie:~/OpenDiablo2 $ env GOOS=linux GOARCH=arm64 go build .
package github.com/OpenDiablo2/OpenDiablo2
        imports github.com/OpenDiablo2/OpenDiablo2/d2app
        imports github.com/OpenDiablo2/OpenDiablo2/d2common/d2util
        imports github.com/hajimehoshi/ebiten/v2
        imports github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw
        imports github.com/hajimehoshi/ebiten/v2/internal/devicescale
        imports github.com/hajimehoshi/ebiten/v2/internal/glfw
        imports github.com/go-gl/glfw/v3.3/glfw: build constraints exclude all G                     o files in /home/pi/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-2020070708                     2815-5321531c36a2

**Comment by Exarkuniv** [comment]
just jumped on
