### ISSUE TITLE
can only walk in game - no mobs - no interactions 

### ISSUE THREAD

**Issue by mandros1985** [OpenDiablo2/OpenDiablo2#1136]
**Describe the bug**
can only walk - no mobs - no interactions 

When running the game on my macos I cannot do anything except walk 

the inventory cannot be moved from slots 
there are no mobs anywhere 
cannot interact with any npcs 

when creating a character all the quests are already done ?! 

d2 + lod 

Game runs but I am unable to play 

**Expected behavior**
I am able to play the game

**Desktop (please complete the following information):**
 - OS: macos catalina 
 - Version 10.15.7

**Comment by ThomasChr** [comment]
You've read the current status?
https://github.com/OpenDiablo2/OpenDiablo2/blob/master/docs/status.md

The game is nowhere near completion. We're working on it, but yes, there not much more than walking around town at the moment.

Maybe you want to learn some go and join the coding fun? :-)

**Comment by mandros1985** [comment]
That would make sense ;) I thougt this might be like openra - I see 

Thanks for the update I will look into it
