### ISSUE TITLE
Reddit github link is wrong

### ISSUE THREAD

**Issue by DarthGandalf** [OpenDiablo2/OpenDiablo2#1137]
**Describe the bug**

https://www.reddit.com/r/OpenDiablo2/ points at github.**org** but should be pointing at github.**com**

**To Reproduce**
1. Go to https://www.reddit.com/r/OpenDiablo2/

**Expected behavior**
The github link is correct

**Screenshots**

![Выделение_382](https://user-images.githubusercontent.com/325092/126453114-8edf9776-414b-4065-abc3-ed5aaee2e2b2.png)

**Desktop (please complete the following information):**
Irrelevant: this doesn't depend on my OS and browser, or on version

**Additional context**

**Comment by gravestench** [comment]
fixed, thank you.
