### ISSUE TITLE
scrolling is super quick when first entering the map test

### ISSUE THREAD

**Issue by mewmew** [OpenDiablo2/OpenDiablo2#116]
**Describe the bug**
If you enter the map test and then try to scroll, sometimes the scroll is really quick and not smooth as it should be. After the first few seconds of the game, then scrolling is always smooth.

I think this is an issue with the calculation of delta time used for scrolling. Where perhaps a lot of time has passed for the first scroll interaction.

Note, this is on rev a105bb390a8641b8b5b2c024b6e65d2c8b775a5b

**Comment by essial** [comment]
Yeah delta time needs a "falco punch" check. I'm adding that today!

**Comment by essial** [comment]
I'm giong to leave this as an easy issue for someone new. Basically there's a function that does an update loop until we 'catch up'. It needs to be changed to just do the update once, then set the last update time to the current time.

**Comment by essial** [comment]
Do note that I'd like to keep delta time (as a ratio of 1 second), though I'm cool with limiting it to some max delta to keep things from going crazy (maybe a tenth of a second). runtimeNano() is a function that may be of use as i was told that the date time module can be quite heavy.

**Comment by essial** [comment]
Should be fixed with #123
