### ISSUE TITLE
Travis CI Not working

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#142]
Just putting a placeholder here. A few days back TravisCI suddenly lost the ability to deploy releases to Github. I have no idea what the issue is currently.

**Comment by zelahi** [comment]
Hi I wanted to take a look and try to fix this issue, however I am wondering how its being released.  Are you guys tagging the builds beforehand?  Just wondering how that is being done as I see this: 
https://github.com/OpenDiablo2/OpenDiablo2/blob/master/.travis.yml#L41-L42.

So I assume that it can only be released when the build is tagged.  I went in and saw that the only tag is `dev`.  I'm wondering, would you like something included in the `.travis.yml` which tags a build on master whenever there is a merge to that branch?

**Comment by essial** [comment]
OK, so I won't pretend to know anything about anything when I set that up. Basically I just want to create a new build every time a PR is merged into master. We also need to make sure it supplies the changeset and branch info in the build as it does in the travis yaml.

I don't care if it's travis or github, just want the builds to work. Also note that we also have the HellSpawner toolkit that will need similar love.

**Comment by essial** [comment]
I'd also like to note that I want to prevent having 8000 tags and releases. I just want one release for the absolute latest version in master for now.

**Comment by zelahi** [comment]
ahh gotcha, I hope its okay but I believe this PR should help deploy the latest changes to master.  I'm not too familiar with TravisCi, but it seemed to work on what I had in my personal fork
