### ISSUE TITLE
[QUESTION] Is it possible to play on Linux?

### ISSUE THREAD

**Issue by guilhermehubner** [OpenDiablo2/OpenDiablo2#148]
I have the original disks from Diablo 2. Is it possible to play on Linux? Case it is, how can I do it?

**Comment by money123451** [comment]
install from the disks with wine (and the DLC) and then patch to the latest and then take the mpqs from the install and that is all you need.

**Comment by essial** [comment]
This game requires the MPQs from both Diablo2 and the LOD expansion. Generally speaking we only currently support the latest patch as well. The best way is to install D2/LOD with Wine, and connect to battle.net to grab the latest updates. Then point the config of this project to those files. Other methods may work but are not supported.
