### ISSUE TITLE
Create github action for continuous builds

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#158]
For some reason, github is no longer letting travis CI push builds up. We need to add support for github actions to update the development build when commits are pushed. The travis CI file is in this repo and can be used as a reference.

What should happen is when a pull request is merged, it should trigger a build to update the OpenDiablo (Unstable) release.

**Comment by liberodark** [comment]
Im use this configuration for build : https://github.com/liberodark/ODrive/blob/master/.travis.yml

**Comment by essial** [comment]
Where is $GITHUB_TOKEN defined? Is this built into travis or is this a protected variable in travis.

**Comment by liberodark** [comment]
![image](https://user-images.githubusercontent.com/4238928/68806154-8e795000-0665-11ea-9b9b-8afd7a88b2e9.png)

**Comment by essial** [comment]
Gotcha

**Comment by liberodark** [comment]
That is in settings of : is exemple https://travis-ci.org/OpenDiablo2/OpenDiablo2/settings

**Comment by Smolevich** [comment]
> Where is $GITHUB_TOKEN defined? Is this built into travis or is this a protected variable in travis.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret
