### ISSUE TITLE
Failed to load specified MPQ file: Patch_D2.mpq

### ISSUE THREAD

**Issue by axiaorong** [OpenDiablo2/OpenDiablo2#170]
When i run program,it tips me the failed.And i also run after go get -d.How could i do.Help god guys

**Comment by liberodark** [comment]
Hi you have modified the config.json ?

**Comment by axiaorong** [comment]
yes，like this&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liberodark"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午3:42
收件人: "OpenDiablo2/OpenDiablo2"<OpenDiablo2@noreply.github.com&gt;; 
抄送: "P C R"<925418578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenDiablo2/OpenDiablo2] Failed to load specified MPQ file: Patch_D2.mpq (#170)




Hi you have modified the config.json ?

**Comment by liberodark** [comment]
Send me your config.json

**Comment by axiaorong** [comment]
{
&nbsp; &nbsp; "Language": "ENG",
&nbsp; &nbsp; "FullScreen": true,
&nbsp; &nbsp; "Scale": 1,
&nbsp; &nbsp; "TicksPerSecond": -1,
&nbsp; &nbsp; "RunInBackground": true,
&nbsp; &nbsp; "VsyncEnabled": true,
&nbsp; &nbsp; "SfxVolume": 1.0,
&nbsp; &nbsp; "BgmVolume": 0.3,
&nbsp; &nbsp; "MpqPath": "C:/Program Files (x86)/Diablo II",
&nbsp; &nbsp; "MpqLoadOrder": [
&nbsp; &nbsp; &nbsp; &nbsp; "Patch_D2.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2exp.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2xmusic.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2xtalk.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2xvideo.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2data.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2char.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2music.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2sfx.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2video.mpq",
&nbsp; &nbsp; &nbsp; &nbsp; "d2speech.mpq"
&nbsp; &nbsp; ]&nbsp; &nbsp;&nbsp;
}







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liberodark"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午3:44
收件人: "OpenDiablo2/OpenDiablo2"<OpenDiablo2@noreply.github.com&gt;; 
抄送: "P C R"<925418578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenDiablo2/OpenDiablo2] Failed to load specified MPQ file: Patch_D2.mpq (#170)




Send me your config.json

**Comment by liberodark** [comment]
Thanks you have Windows 10 ?
And your game is in this folder: C:/Program Files (x86)/Diablo II ?

**Comment by axiaorong** [comment]
it mean must have this game,but i've never downloaded it.Thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liberodark"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午3:51
收件人: "OpenDiablo2/OpenDiablo2"<OpenDiablo2@noreply.github.com&gt;; 
抄送: "P C R"<925418578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenDiablo2/OpenDiablo2] Failed to load specified MPQ file: Patch_D2.mpq (#170)




Thanks you have Windows 10 ?
 And your game is in this folder: C:/Program Files (x86)/Diablo II ?

**Comment by essial** [comment]
For anyone else with this issue -- although the ENGINE is cross platform, we can only officially support installing diablo 2 and LOD with the official installers. There may be other ways to get it working, but I'm doing everything I can to prevent getting a cease and desist letter. The engine is simply looking for the files, so ultimately, that's all it really cares about. Install it in windows, on a VM, or with wine, and copy the files over.

**Comment by YurisaX** [comment]
> When i run program,it tips me the failed.And i also run after go get -d.How could i do.Help god guys
in windows you can modified the config.json like this.
...
"MpqPath": "C:\\Diablo2", 
...

**Comment by rusnasonov** [comment]
Same issue.

OSX 10.14.6, go 1.13.4. Use master branch for build project, `go get github.com/OpenDiablo2/OpenDiablo2` from README. Fix config, change `MpqPath` to `$GOPATH/src/github.com/OpenDiablo2/OpenDiablo2`.

```
2019/11/15 07:03:54.082119 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:35: OpenDiablo2 - Open source Diablo 2 engine
2019/11/15 07:03:54.086992 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:93: Loading configuration file
2019/11/15 07:03:54.087529 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:122: Failed to load specified MPQ file: Patch_D2.mpq
```

**Comment by essial** [comment]
> Same issue.
> 
> OSX 10.14.6, go 1.13.4. Use master branch for build project, `go get github.com/OpenDiablo2/OpenDiablo2` from README. Fix config, change `MpqPath` to `$GOPATH/src/github.com/OpenDiablo2/OpenDiablo2`.
> 
> ```
> 2019/11/15 07:03:54.082119 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:35: OpenDiablo2 - Open source Diablo 2 engine
> 2019/11/15 07:03:54.086992 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:93: Loading configuration file
> 2019/11/15 07:03:54.087529 /Users/perseus/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:122: Failed to load specified MPQ file: Patch_D2.mpq
> ```

Try these settings:
    "MpqPath": "/Applications/Diablo II",
    "MpqLoadOrder": [
        "Diablo II Patch",
        "Diablo II Expansion Data",
        "Diablo II Expansion Music",
        "Diablo II Expansion Speech",
        "Diablo II Expansion Movies",
        "Diablo II Game Data",
        "Diablo II Speech",
        "Diablo II Music",
        "Diablo II Sounds",
        "Diablo II Movies",
        "Diablo II Speech"
    ]

**Comment by rusnasonov** [comment]
My bad. I skip this in README

> You must have a legally purchased copy of Diablo 2 and its expansion Lord of Destruction installed on your computer in order to run that game on this engine.

I thought that this project is Diablo2 written in Golang from the scratch =)

**Comment by essial** [comment]
"OpenDiablo2 is an ARPG game engine in the same vein of the 2000's games, and supports playing Diablo 2. The engine is written in golang and is cross platform. However, please note that this project does not ship with the assets or content required to play Diablo 2."

If we distributed the original game data, we would be immediately sued for software piracy and shut down.
