### ISSUE TITLE
cursor and viewport render at low FPS

### ISSUE THREAD

**Issue by kroppt** [OpenDiablo2/OpenDiablo2#189]
**Describe the bug**
A recent commit removed high-framerate rendering. I would expect, like prior to the commit, that the viewport and mouse render at a high frame rate, even if sprites aren't.

The commit at and after which this issue occurs: 4c9f0ec03e6fd892f50cbc624a0e49850d2ec30d

**To Reproduce**
1. Disable V-Sync
2. Set tick rate to >60 or -1
3. Press F6

The frame rate goes as high as 57.

**Expected behavior**
The frame rate should be as high as it's set to, or as high as possible if uncapped.

**Desktop (please complete the following information):**
 Windows 10

**Comment by essial** [comment]
Can you please add the following to the first line of main() in main.go:
`defer profile.Start(profile.ProfilePath(".")).Stop()`
And reply with the attached cpu.pprof file after running letting it run for a few minutes?

This commit was specifically to address animation speed issues, and a lowering of FPS is not expected at all.

**Comment by kroppt** [comment]
CPU usage was ~2-3%
GPU usage was ~2%
FPS went up to 57.
Moved around the map test for a bit.
Profile attached. I had to add .log extension to the file for GitHub to accept it.
[cpu.pprof.log](https://github.com/OpenDiablo2/OpenDiablo2/files/3854566/cpu.pprof.log)

**Comment by essial** [comment]
I've been poking around and have noticed a similar issue where it is running around 57fps steady for what seems like no reason. I will look into this more closely tonight!

**Comment by essial** [comment]
I've tracked this down to ebiten. At v1.10 it runs at 600+fps, at the current revision it's capped at 57fps. I will let him know as soon as he wakes up and he'll take a look at it.

**Comment by essial** [comment]
He has found the issue and is working on a fix.

**Comment by essial** [comment]
More info... This is a GLFW bug where windows always reports 0 when the window is queried to see if it is focused. Do you happen to have a monitor with GSYNC enabled?

**Comment by kroppt** [comment]
My monitor does not support G-Sync.
It's also a 144 Hz monitor, hence why I noticed the issue immediately.
I have AMD graphics card.

**Comment by essial** [comment]
This issue has been resolved in the ebiten library. I'll be closing this issue when I merge the new hash.
