### ISSUE TITLE
POLL: Graphics API or Gameplay

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#190]
OK guys, I've spent a lot of time fighting micro-issues with the graphics API. As I am the core developer for the low level stuff, I will most likely be the one implementing the core gameplay logic as well.

Because of this, I need to focus on one thing, and would like to know what everyone would prefer...
Thumbs up for **gameplay**
Thumbs down for **graphics api**

**Comment by essial** [comment]
Thumbs up for **gameplay**

**Comment by Myles-Glass** [comment]
Thumbs up for me, as long as the scope remains "core." I think once there is a base to work off of, contributors will start helping a lot more.

**Comment by essial** [comment]
Yeah hajimehoshi is trying to fix the issues we're having with his library, so it may be good to give him some more time to try to get things working before we rip it out and go with our own API.

**Comment by essial** [comment]
OK I'll close this issue then. He just added a patch that made one guy's load times go from 8 minutes to 8 seconds, so I feel that his library is moving in the right direction.
