### ISSUE TITLE
Suggestion: Add screenshot of in-game to increase engagement.

### ISSUE THREAD

**Issue by fabiensanglard** [OpenDiablo2/OpenDiablo2#217]
So far the project features only title screenshots. If the rewrite has managed to go further than that suggest to add screenshots of it. 

Alternatively, it would be cool to be able to follow progress with a "current state" section in README.md

**Comment by essial** [comment]
That's a very good point, we are very much past this point. I'll do this tonight!

**Comment by essial** [comment]
#218
