### ISSUE TITLE
no gui and character not moving

### ISSUE THREAD

**Issue by ludal13** [OpenDiablo2/OpenDiablo2#227]
Hi,

I'm facing a weird problem.
I'm trying to play on MacOS 10.15.1.

Game is successfully launched with `go run .`, I can create / delete characters, but when I "enter" the game, there is nothing I can do:
- I have no GUI
- character can not move
- impossible to exit the game

I can see these logs in the console :

```
2019/11/22 14:40:32.264547 /XXX/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:144: Could not load data\global\chars\dz\hd\dzhdlittn1hs.dcc from MPQs
2019/11/22 14:40:32.267184 /XXX/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:144: Could not load data\global\chars\dz\la\dzlalittn1hs.dcc from MPQs
2019/11/22 14:40:32.269182 /XXX/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:144: Could not load data\global\chars\dz\lg\dzlglittn1hs.dcc from MPQs
2019/11/22 14:40:32.274837 /XXX/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:144: Could not load data\global\chars\dz\sh\dzshbuctn1hs.dcc from MPQs
2019/11/22 14:40:32.276788 /XXX/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:144: Could not load data\global\chars\dz\tr\dztrlittn1hs.dcc from MPQs
```
I am not sure what the problem is here... are my MPQ files bad ?

Thanks !

**Comment by essial** [comment]
This is as far as we have right now. Until the toolset is extended we cannot add gameplay as we would have to then rip it right back out. Sorry to disappoint you but we are working as hard as we can!

**Comment by ludal13** [comment]
Hi,

Thank you for your answer :)
It's not a disappointment ! You've a done a terrific work so far.

I'll keep looking at the project ;)

Thanks.
