### ISSUE TITLE
Error on parsing unique items

### ISSUE THREAD

**Issue by j0y** [OpenDiablo2/OpenDiablo2#236]
Starting OpenDiablo2 leads to error:

> 2019/11/25 16:52:31.959220 OpenDiablo/OpenDiablo2/main.go:41: OpenDiablo2 - Open source Diablo 2 engine
> 2019/11/25 16:52:31.965358 OpenDiablo/OpenDiablo2/d2core/engine.go:96: Loading configuration file
> 2019/11/25 16:52:32.017768 OpenDiablo/D2Shared/d2data/d2datadict/palette.go:49: Loaded 18 palettes
> 2019/11/25 16:52:32.051082 OpenDiablo/D2Shared/d2common/text_dictionary.go:36: Loaded 8926 entries from the string table
> 2019/11/25 16:52:32.051409 OpenDiablo/D2Shared/d2data/d2datadict/level_types.go:55: Loaded 38 LevelType records
> 2019/11/25 16:52:32.054732 OpenDiablo/D2Shared/d2data/d2datadict/level_presets.go:92: Loaded 1090 level presets
> 2019/11/25 16:52:32.055262 OpenDiablo/D2Shared/d2data/d2datadict/level_warp.go:52: Loaded 83 level warps
> 2019/11/25 16:52:32.058446 OpenDiablo/D2Shared/d2data/d2datadict/object_types.go:34: Loaded 573 object types
> 2019/11/25 16:52:32.065331 OpenDiablo/D2Shared/d2data/d2datadict/objects.go:356: Loaded 571 objects
> 2019/11/25 16:52:32.081617 OpenDiablo/D2Shared/d2data/d2datadict/weapons.go:17: Loaded 307 weapons
> 2019/11/25 16:52:32.088688 OpenDiablo/D2Shared/d2data/d2datadict/armor.go:17: Loaded 203 armors
> 2019/11/25 16:52:32.093331 OpenDiablo/D2Shared/d2data/d2datadict/misc.go:17: Loaded 140 misc items
> panic: strconv.Atoi: parsing "hax": invalid syntax
> 
> goroutine 1 [running, locked to thread]:
> github.com/OpenDiablo2/D2Shared/d2helper.StringToInt(...)
>         OpenDiablo/D2Shared/d2helper/stringutils.go:33
> github.com/OpenDiablo2/D2Shared/d2data/d2datadict.createUniqueItemRecord(0xc000f3bc00, 0x37, 0x37, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         OpenDiablo/D2Shared/d2data/d2datadict/unique_items.go:73 +0x11d4
> github.com/OpenDiablo2/D2Shared/d2data/d2datadict.LoadUniqueItems(0xa9d820, 0xc0001ba100)
>         OpenDiablo/D2Shared/d2data/d2datadict/unique_items.go:135 +0x2b9
> github.com/OpenDiablo2/OpenDiablo2/d2core.CreateEngine(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
>         OpenDiablo/OpenDiablo2/d2core/engine.go:79 +0x202
> main.main()
>         OpenDiablo/OpenDiablo2/main.go:47 +0x172

I added `fmt.Printf("x = %#v \n", r)` to [unique_items.go#L63](https://github.com/OpenDiablo2/D2Shared/blob/master/d2data/d2datadict/unique_items.go#L63) and got following output before the error:

> x = []string{"The Gnasher", "0", "1", "1", "1", "7", "5", "hax", "Hand Axe", "5", "5000", "1", "0", "14", "att", "", "30", "30", "openwounds", "", "50", "50", "crush", "", "20", "20", "dmg%", "", "60", "70", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "0"}

**Comment by Dragomir-Ivanov** [comment]
Please, make sure you are using Diablo 2 v1.14. I had such issues like yours with older versions.

**Comment by j0y** [comment]
Checked again. Turns out I had wrong patch_d2.mpq file.
