### ISSUE TITLE
config.json should be config.go

### ISSUE THREAD

**Issue by JoSSte** [OpenDiablo2/OpenDiablo2#297]
**Describe the bug**
in readme.md the configuration file is described as config.json. this should be config.go

**Comment by essial** [comment]
Incorrect, config.go defines the default configuration. The game actually loads the config.json file if one exists. In the future, any changes to the default settings will also be written to config.json.

https://github.com/OpenDiablo2/OpenDiablo2/blob/554a2765204370ecf91ca80a5d7a6d0b999c4c10/d2core/d2config/d2config.go#L44

**Comment by essial** [comment]
And just for more clarification, we used to ship with a config.json but people kept having issues with having to exclude it from commits, so it was decided to omit it from source control completely.

**Comment by JoSSte** [comment]
okay. then maybe adding the spec of the file would be benefitiary. i went hunting for it, and found no useful information, but ended up altering the config.go file de to a lack of better knowledge

**Comment by Ziemas** [comment]
I'm confused, the json file is automatically created if it doesn't exist. Or did that break at some point?

**Comment by JoSSte** [comment]
I just did a `dir /a /s /b > files.txt` and attached the file here: 
[files.txt](https://github.com/OpenDiablo2/OpenDiablo2/files/4174031/files.txt)
i hadn't heard of this project before yesterday, so my machine is a clean install... only issue was that i had an old version of golang, which I had to upgrade. I can try a reinstall if it would help
