### ISSUE TITLE
Character can get stuck

### ISSUE THREAD

**Issue by j0y** [OpenDiablo2/OpenDiablo2#302]
Character can get stuck with no way to go.

A way to reproduce is to set event.X and event.Y to (325, 203) in OnMouseButtonDown() 
or walk around the crate https://i.imgur.com/qZ6xmvg.png

Probably because of the teleportation to target coordinates once it gets close enough in Step function.

**Comment by essial** [comment]
Yeah, I've also noticed that if you're 1 subtile below a collision it can sometimes get stuck. I'll fix this as I work on the map engine this week.

**Comment by essial** [comment]
Closing this now as the map engine has been re-written. If this happens again I'll open the issue up (unless someone beats me to it).

**Comment by essial** [comment]
Reopening, I got stuck again.

**Comment by Natureknight** [comment]
I'm thinking about implementing path types, which also include and possibly will cover such cases when the player is not able to find path. In case of object collision, the path returned will have type something like PATH_NORMAL, in case we could not find a proper path, so we can decide whether we have to build shortcut path in such cases where the path type is not PATH_NORMAL, hope you got my idea.

**Comment by essial** [comment]
We actually plan on totally removing pathfinding for now. It's preventing 16-direction movement among issues such as this one. Eventually we'll add it back in, but in a way that makes more sense.

**Comment by essial** [comment]
Closing due to #467
