### ISSUE TITLE
PS Vita, Android, or switch ports?

### ISSUE THREAD

**Issue by SHMAUS-Carter** [OpenDiablo2/OpenDiablo2#306]
Are there any plans to Port this engine to the PS Vita, Nintendo switch, or Android once it gets to a stable enough state?

**Comment by liberodark** [comment]
The game is not ending.
Need more time for work in all point of the game and engine.
But later probably have possibility to make port.
This is to take tweezers.
It is possible not sure.

**Comment by essial** [comment]
I don't personally have plans to port to these devices, but I'm not against someone doing work to port the engine to other platforms. I'll be more than happy to accept PRs that add more supported platforms.
