### ISSUE TITLE
FreeBSD port

### ISSUE THREAD

**Issue by nunotexbsd** [OpenDiablo2/OpenDiablo2#324]
Hello,

I'm trying to build OpenDiablo 2 on FreeBSD 12.1 amd64:

`go get github.com/OpenDiablo2/OpenDiablo2
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../go/src/github.com/go-gl/glfw/v3.3/glfw/c_glfw_linbsd.go:18:
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:53:34: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:53:54: error: use of undeclared identifier 'BTN_MISC'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:61:27: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:63:17: error: use of undeclared identifier 'ABS_HAT0X'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:63:38: error: use of undeclared identifier 'ABS_HAT3Y'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:72:33: error: use of undeclared identifier 'ABS_HAT0X'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:73:34: error: use of undeclared identifier 'ABS_HAT0X'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:74:26: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:89:49: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:92:31: error: incomplete definition of type 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:89:22: note: forward declaration of 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:92:47: error: incomplete definition of type 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:89:22: note: forward declaration of 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:96:44: error: incomplete definition of type 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:89:22: note: forward declaration of 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:109:32: error: use of undeclared identifier 'ABS_CNT'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:111:17: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:114:43: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:116:13: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:116:23: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:116:33: warning: implicit declaration of function 'EVIOCGABS' is invalid in C99 [-Wimplicit-function-declaration]
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:119:38: error: incomplete definition of type 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:114:16: note: forward declaration of 'struct input_absinfo'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:133:41: error: no member named 'linjs' in 'struct _GLFWjoystick'
../go/src/github.com/go-gl/glfw/v3.3/glfw/glfw/src/linux_joystick.c:137:23: error: expected ';' after expression
fatal error: too many errors emitted, stopping now [-ferror-limit=]`

I'm using:

[glfw-3.3.2](https://www.freshports.org/graphics/glfw/)                     Portable framework for OpenGL development
[libinotify-20180201_1](https://www.freshports.org/devel/libinotify/)          Kevent based inotify compatible libraryan

Can anyone try a [FreeBSD VM](https://download.freebsd.org/ftp/releases/VM-IMAGES/12.1-RELEASE/amd64/Latest/) to get this engine working on FreeBSD?

Thanks,

Nuno Teixeira

**Comment by gravestench** [comment]
seems like [a known issue with go-gl](https://github.com/go-gl/glfw/issues/264), which ebiten is using.

**Comment by jamesmintram** [comment]
PR upstream: https://github.com/go-gl/glfw/pull/285

**Comment by gravestench** [comment]
I can confirm that this builds and runs on FreeBSD, tested in a vm.
