### ISSUE TITLE
Add TCP/IP networking support

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#331]
The new networking layer currently only supports local connections. We need to add the ability to host a game and connect to a game directly via an IP address. We _cannot_ implement matchmaking as this would violate Blizzard's "copy protection" scheme used in battle.net, and would get us shut down quick. We simply need to be able to host a game, or connect to a game via an IP address similar to how it works in the original game (without battle.net).

**Comment by stephenhoran** [comment]
What does “match making” include? A portal of available games or automatically joining a game?

**Comment by essial** [comment]
Matchmaking meaning you can be matched up automatically or directly with other players inside the game, and have the game run on the server. Basically we can't clone battle.net as blizzard considers that their copy protection, and cloning that would run us afoul of their lawyers from what I've seen.
