### ISSUE TITLE
Finish ebiten separation

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#337]
All ebiten package references should be exclusively referenced in the d2render/ebiten package. There are currently other parts of the engine that reference ebiten directly. In order to facilitate porting, we need to separate it out.

**Comment by carrelld** [comment]
I'm seeing a lot of references to input handled by ebiten. Are you imagining putting these calls behind an interface?

**Comment by essial** [comment]
Yeah, we separated a lot of it already, but some of it is still hardwired in.

**Comment by carrelld** [comment]
I'd like to take this on. I'm having trouble knowing exactly the boundaries of ebiten. But I suspect d2input, d2audio, and d2render all use ebiten, but anything accessing these should be through the respective package interface without referencing the library at all.

**Comment by essial** [comment]
Basically the only files that should reference ebiten in the imports is in the ebiten implementation package. I've assigned it to you. Please let me know if you decide not to work on it so I can un-assign. Good luck!
