### ISSUE TITLE
Implement streaming for MPQ data loads

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#349]
Currently MPQ file loading returns the file as a byte array. We need to change this to instead return a stream reader (most likely will require using channels under the hood). This is necessary because some assets do not need to be fully loaded all at once (especially music).

This is a pretty big task, and I'm ok with initially having stream reading implemented just for the music for now, then expanded to everything else.

**Comment by jybp** [comment]
gimme

**Comment by essial** [comment]
Aaaand it's yours!
