### ISSUE TITLE
Escape Menu support

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#353]
We need to implement the escape menu on the game so that players can leave the game, adjust settings, etc. This is that big menu that comes up when you hit ESC during gameplay. For now, just being able to call it up and have stub functions executed if they select an option is good enough for this task.

Also, for single player games, this should cause the game to pause in the background.

**Comment by aziule** [comment]
Hey there, if that's fine for you I'd like to try this as a first issue on this project.

**Comment by malavv** [comment]
Wait @aziule, I might have something already. Sorry I didn't mention anything first.

**Comment by aziule** [comment]
@malavv  no worries, nice PR though!

You actually handled something I didn't: mouse actions - I only handled keyboard actions with up/down/enter keys.

If you are not handling it in your PR then I might add it.

**Comment by malavv** [comment]
Yep, good catch. Mine doesn't handle keyboard event. It's all yours.
