### ISSUE TITLE
Character stats and relevant UI

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#354]
We need to ensure character stats get transferred during character joins to the game. Additionally, we need the HP and MP bars on the UI to properly render based on the player's stats. We also need the stats screen to render the player's stats values properly.

**Comment by presiyan-ivanov** [comment]
Hey, I can take this issue if its okay.

**Comment by essial** [comment]
Sure! Sorry I thought I assigned you earlier but I’ll do it now.

**Comment by essial** [comment]
Thanks!
