### ISSUE TITLE
Add a linter to the pipeline

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#355]
We need to add a linter as part of the pull request check. This will obviously fail on every PR for now, but we at least need it in place so that once we clean things up, we can keep the code nice and clean.

**Comment by ewohltman** [comment]
I can help with this. I've set up `golangci-lint` with a number of repos using GitHub actions that may be useful.

**Comment by essial** [comment]
Sure, go for it! I've got you assigned.
