### ISSUE TITLE
Add code comments to everything

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#356]
All of the existing code is poorly documented (if at all). Everything needs to be properly commented (functions, parameters, etc). This will require a lot of effort over time, but if you want to comment a specific section, please make a comment below so we don't step on each other's toes.

**Comment by danhale-git** [comment]
You can run a local server to view the docs generated for your current local version, enabling you to check the generated formatting against your comments before making pull requests:
`godoc -http=:6060`
https://blog.golang.org/godoc

For anyone who is new to go, comments have some very specific conventions
https://golang.org/doc/effective_go.html#commentary

Linting should warn you about common things like adding comments to all exported functions, starting with the function name.

`// ExportedFunc does stuff with things
func ExportedFunc() {
}`

Your comments automatically generate public documentation at [godoc.org/github.com/OpenDiablo2/OpenDiablo2/](https://godoc.org/github.com/OpenDiablo2/OpenDiablo2/d2common/d2data#LoadAnimationData).

**Comment by ewohltman** [comment]
PR https://github.com/OpenDiablo2/OpenDiablo2/pull/427 should help enforce the application of godoc style comments.

**Comment by gravestench** [comment]
Yeet!
