### ISSUE TITLE
Player Equipment UI

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#357]
We need to properly render the player's equipment in the inventory UI. Mouse interaction isn't necessary at this point in time, but we at least need to show what they have equipped. This ONLY includes showing the images. Hovering over the equipment does not need to show the equipment's stats.

**Comment by Ripolak** [comment]
I'd love to try taking this issue.

**Comment by essial** [comment]
OK I've assigned it to you, please let me know if you give up on it so I can un-assign it. Good luck!

**Comment by Ripolak** [comment]
https://github.com/OpenDiablo2/OpenDiablo2/pull/419

**Comment by essial** [comment]
#421 Added. Thanks!
