### ISSUE TITLE
Javascript console commands

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#367]
We need to extend the debug console to allow javascript commands. This should not be usable when connected to a multiplayer game as a remote client. We should have the command in the following format:

`js <javascript code>`

As an example:
`js debugWrite("Hello world!")`

**Comment by aziule** [comment]
Are you only looking for an interpreter here, so you can use the JS syntax to execute some code, or is it something else/more?

**Comment by essial** [comment]
We have a JVM already implemented in d2script, we just need a way to call into it from the console.

**Comment by aziule** [comment]
I can try this one

**Comment by essial** [comment]
Assigned.

**Comment by aziule** [comment]
Do we want to allow JS commands (= access to the script engine) outside a game, like from the main screen, character selection, etc. or should that be only made available when the server starts?

**Comment by essial** [comment]
It should only be accessible during a game, and only if you're host or single player.
