### ISSUE TITLE
Object offsets in stamps

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#392]
When stamping onto the map, the code transfers the entities from the stamp to the map engine. The problem is, it does not consider the offset of the stamp, causing the objects/entities to be placed at the base x/y positions without offsets - this problem extends to the path x/y locations as well. We need to fix it so that the x/y positions get adjusted when stamping (as in, it can't be done at stamp load time, it has to be done on the clone that is created).

**Comment by gravestench** [comment]
Is this still an issue? I was going over the d2map files and couldn't determine where this issue would be. It seems that `MapEngine` is placing the stamps with the (mapTile + stampTile) offsets.

**Comment by essial** [comment]
It’s not, forgot to close out.
