### ISSUE TITLE
Add the options selection menu

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#394]
When clicking options in game, it should show the following list:

SOUND OPTIONS
VIDEO OPTIONS
AUTOMAP OPTIONS
CONFIGURE CONTROLS
PREVIOUS MENU

Only thing that needs to be implemented is the "previous menu" option, though you should be able to click on the other options and it should print out that it was clicked like the main escape menu does today.

**Comment by aziule** [comment]
Hey, I can take this one if that's fine for you

**Comment by essial** [comment]
Assigned, let me know if you change your mind so I can un-assign. Good luck!
