### ISSUE TITLE
Support client disconnects in the networking layer

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#396]
When a client disconnects, we need to detect this and either remove them from the game (in the case of a client connection), or disconnect all of the clients (in the case of the host leaving). For now it is acceptable to just close out the game with a message printed until we support leaving the game back to the main menu.

**Comment by stephenhoran** [comment]
Could this be assigned to me? I have some of this sorted out, hopefully :).

**Comment by essial** [comment]
Sure thing! Just message back if you give up on this so I can un-assign. Good luck!

**Comment by gravestench** [comment]
@stephenhoran did you make any progress?

**Comment by stephenhoran** [comment]
@gravestench the network stack does handle disconnects but looking at this now it do not remove the disconnected user sprite from the game.

**Comment by ianling** [comment]
I can take this one
