### ISSUE TITLE
Add ability to leave the game

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#397]
We need to be able to leave the game when you click "Save and exit game" on the escape menu.

**Comment by brendanporter** [comment]
I'll take this on

**Comment by essial** [comment]
Assigned, good luck! Let me know if you change your mind so I can unassign.

**Comment by brendanporter** [comment]
Addressed in https://github.com/OpenDiablo2/OpenDiablo2/pull/450
