### ISSUE TITLE
Add run button

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#400]
Now that run is working (press R to toggle), we need to render the run button the UI, and allow the user to toggle it with their mouse, in addition to the R key on the keyboard. The toggle state should reflect the run state of the user.

**Comment by Natureknight** [comment]
Hey, I can take this one if that's fine for you

**Comment by essial** [comment]
Go for it! Let me know if you decide not to do this so I can un-assign. Good luck!
