### ISSUE TITLE
Player animations for missile casting

### ISSUE THREAD

**Issue by nicholas-eden** [OpenDiablo2/OpenDiablo2#412]
When the player right clicks the hero should stop moving and go through the cast animation.  When the animation is finished, the current missile should spawn.

**Comment by carrelld** [comment]
I guess I'll try this one now

**Comment by carrelld** [comment]
Looks like the missile code currently implemented in `game_controls.go` but `MovePlayer` is implemented in the `game_client.go` behind the server/client stuff. Where did you imagine this being implemented?

**Comment by essial** [comment]
There is currently no mechanism that I know of to handle casting animations. This will have to be implemented. I would imagine we send a move player command with the same start and destination location (or a 'place player' command that puts it in a specific spot, and puts them into a standing state and clears their path queue). Then we need a network packet for casting missiles. When that packet comes in we'll need a way to tell the entity to start the casting animation (as well as creating the actual missiles).

**Comment by carrelld** [comment]
Can it be a single packet? Like CastPacket{skillID, sourceX, sourceY, targetX, targetY} from this, we know exactly where the player is when casting and can position/move them to sourceX,Y. That way we can avoid two packets. 

Let me know if this makes no sense. I'm feeling a bit in the deep end with this project and good game networking practice.

**Comment by essial** [comment]
I'm think there's possibly two destination types.. either a specific X/Y (subtile), OR an entity ID. For source I don't think there's a situation where it wouldn't be coming from some kind of entity. So I'd say have the packet have a source entity ID, and either a destination x/y or destination entity.

**Comment by presiyan-ivanov** [comment]
I implemented this logic with #729 - the issue can be closed in my opinion.

**Comment by gravestench** [comment]
@presiyan-ivanov good work, and thank you!
