### ISSUE TITLE
Bottom panel interactivity

### ISSUE THREAD

**Issue by nicholas-eden** [OpenDiablo2/OpenDiablo2#413]
There's lots of things that can be done for the bottom panel:

- Fill the health and mana with a red/blue circle based on a percent input
- Trigger respective panels (or just log) when the user clicks on the buttons

**Comment by essial** [comment]
This auto-closed. Re-opening as there is much to do.

**Comment by essial** [comment]
#436

**Comment by Natureknight** [comment]
Can we close this one?

**Comment by essial** [comment]
We can, it seems to work well now!
