### ISSUE TITLE
run.sh script fails on arch/manjaro if you have mesa-git installed

### ISSUE THREAD

**Issue by HughJass** [OpenDiablo2/OpenDiablo2#437]
The run.sh script tries to install mesa, but if you are using mesa-git it'll conflict and the script fails. It should have a check if you have mesa-git installed and if so, skip installation of mesa

**Comment by essial** [comment]
Can you pull latest and verify this issue is fixed?

**Comment by HughJass** [comment]
I pulled and the run.sh script is gone. There is build.sh but it has the same bug. Are you talking about different branch ?

**Comment by essial** [comment]
There were changes to run.sh and it was renamed to build.sh. If it's still present then I'll leave the issue open. If no one fixes this soon I'll install a VM and test myself.

**Comment by HughJass** [comment]
I don't even see an attempt to fix it in the current build.sh. Fix could look something like this:

**Comment by essial** [comment]
Did you mean to close this issue? If it's still a problem leave it open so we can get this working.

**Comment by HughJass** [comment]
I don't even see an attempt to fix this issue in the current build.sh The fix could be something like this:
MESA_GIT_PRESENT=$(pacman -Q | grep mesa)
DEPS= "package1 package2 package3"
if [ -z ${MESA_GIT_PRESENT} && DEPS=${DEPS} mesa

No I accidentaly posted before finishing my post and I just removed it

**Comment by HughJass** [comment]
Actually, mesa is such an important package that
1. I doubt someone doesn't have it installed already (unless it's a fresh install)
2. Since it's such an important package I'm not sure if the script should attempt to install it in the first place. Maybe just check if it's installed and if not complain about it.

But that's just my opinion

**Comment by essial** [comment]
Kk, I'll reopen it then, I'd like one of the linux guys to fix this so that others don't run into this issue.

**Comment by Benzhaomin** [comment]
I feel like build.sh is fine as it is. Anybody using AUR or other custom packages can also easily install deps by hand or edit the script or not use it at all really.

**Comment by liberodark** [comment]
> Actually, mesa is such an important package that
> 
>     1. I doubt someone doesn't have it installed already (unless it's a fresh install)
> 
>     2. I'm not sure if the script should attempt to install it in the first place. Maybe just check if it's installed and if not complain about it.
> 
> 
> But that's just my opinion

Is not simple to no add mesa on script

**Comment by liberodark** [comment]
Issue fixed
