### ISSUE TITLE
Interfaces bugs

### ISSUE THREAD

**Issue by CthUlhUzzz** [OpenDiablo2/OpenDiablo2#440]
1. Mana and life levels are not displayed in the game
2. The buttons of the game interface do not respond to pressing. Instead, the character starts moving behind the cursor.
3. The character freezes when you get close to the game object
4. Escape menu do not responde to pressing  its buttons
5. Game objects do not respond when I hover and click on them

 - OS: Debian 10, KDE
 - Go: 1.14.4
 - OpenDiablo2: latest commit
 - Diablo II: 1.14b

![Screenshot_20200624_211057](https://user-images.githubusercontent.com/6465228/85611806-f151b180-b660-11ea-850f-953318fc4372.png)

**Comment by essial** [comment]
The above mentioned items are all currently tracked as enhancements on the issue tracker except for number 3. Can you explain this one in more detail?

**Comment by CthUlhUzzz** [comment]
If I go to a fence, building or chest, the character freezes and I can no longer control it. Only restarting the game helps

**Comment by essial** [comment]
Ah yes, that's related to #302

**Comment by essial** [comment]
Closing due to all listed issues being covered in other bug/feature requests. Thanks for the report!
