### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by konbick** [OpenDiablo2/OpenDiablo2#454]
Hi,
I am thrilled by this project because I love D2 and love to see it being re-engineered. However, not being familiar with the project I would have loved if there was some information regarding code. Like how is it structured, where do I find what etc. Is there something like this? Otherwise one would have to dig through everything to find something and it just takes much more time to do this code study.
Thanks guys.

**Comment by konbick** [comment]
"main.go is the starting point, other than that, map rendering happens in render.go. the 'main game' stuff is in game.go in d2gamescreen"

**Comment by essial** [comment]
Closing due to not being an issue. We suggest asking in the discord if you have further questions. There is an effort underway to fix all lint issues, which includes proper documentation. Thanks for this submission, and welcome to the group!
