### ISSUE TITLE
Resolve golint warnings

### ISSUE THREAD

**Issue by danhale-git** [OpenDiablo2/OpenDiablo2#487]
Currently there are around 522 warnings and 1700 weak warnings in the project.

Most of these are exported elements that either have no comment or the comment does not start with the element name.

You can check the following links before working on this issue:
https://blog.golang.org/godoc
https://golang.org/doc/effective_go.html#commentary

**Please use the spreadsheet to coordinate work:**
https://docs.google.com/spreadsheets/d/1y6S9-rAB3MMIofSc09RoO9eHGAv76FmmTeHqYjcLzz0/edit?usp=sharing

If you are only updating part of a package, remove your name when you are done.

**Comment by danhale-git** [comment]
I am working on d2networking and everything below it. I plan to take d2map next if it hasn't been taken already.

**Comment by gurkankaymak** [comment]
I've done `d2script` and `d2common/d2interface`packages

**Comment by danhale-git** [comment]
@Ziemas is working on d2datadict

**Comment by Ziemas** [comment]
d2datadict is free again, I didn't do all of it.

**Comment by essial** [comment]
I'm doing d2enum

**Comment by essial** [comment]
Hey I put up a spreadsheet. It's open access, hopefully I can keep it that way. Please mark what you are doing or have finished. If you're only doing part of a package, remove your name from it once you're done with your partial change.

**Comment by gravestench** [comment]
Yeet!
