### ISSUE TITLE
Replace ebiten text with built-in font

### ISSUE THREAD

**Issue by essial** [OpenDiablo2/OpenDiablo2#503]
We need to obtain or create a small pixel-based charmap (8x8 maybe?), of the standard 256 character variety. Then we need to replace DrawText's reliance on DebugPrintAt to instead print characters from the built in charset. That will help de-couple dependency on Ebiten-specific functionality, as well as prevent constant allocations per frame for text.

Please take care to not create allocations where possible as this function can be called a large number of times per frame.

**Comment by thetogi** [comment]
I'm interested in taking a stab at this.

**Comment by essial** [comment]
Assigned. Let me know if you get stuck as we need this pretty soon. Good luck!

**Comment by gravestench** [comment]
@thetogi Are you working on this?

**Comment by thetogi** [comment]
Yes, still working.

**Comment by gravestench** [comment]
![exocet_20x20](https://user-images.githubusercontent.com/936440/86494533-63458d00-bd2a-11ea-9f23-c3ea1b0334d9.png)
![formal_24x24](https://user-images.githubusercontent.com/936440/86494534-63de2380-bd2a-11ea-8683-f59554d7006d.png)

**Comment by gravestench** [comment]
8x15
![noto_sans_mono_8x15](https://user-images.githubusercontent.com/936440/86494775-64c38500-bd2b-11ea-93ff-e3cd82b5bb83.png)

**Comment by thetogi** [comment]
@essial, can you take a look at my d2DebugUtil branch and give any feedback for my changes? Thanks

**Comment by gravestench** [comment]
@thetogi your edits to `go.mod` have an unresolved merge conflict

**Comment by essial** [comment]
Best thing is to create a draft pull request against master so I can see the delta between the two. Makes it easier to see what your changes are.
