### ISSUE TITLE
Issue about font cache

### ISSUE THREAD

**Issue by shengjhen** [OpenDiablo2/OpenDiablo2#515]
**Describe the bug**
The font.go call GetFont access cacheitem with wrong path,because the font path have been changed with loadFile func which locate at filemanager.go.

**Expected behavior**
When font have been load,should not load again,just access the cacheitem.

**Screenshots**
![image](https://user-images.githubusercontent.com/42288446/86268269-81ac6b00-bbfa-11ea-8055-7d7744af77dc.png)

![image](https://user-images.githubusercontent.com/42288446/86267967-0f3b8b00-bbfa-11ea-802c-3c6b1343586f.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by essial** [comment]
Good catch, and great bug report! This is indeed an issue. I wonder if this is causing similar issues for other things as well.

**Comment by malavv** [comment]
I'll take this, if no one mind.

**Comment by shengjhen** [comment]
After the #556 commit,between A and B are equal,but shall we need C and D are independence?
![image](https://user-images.githubusercontent.com/42288446/86916828-c1250b00-c156-11ea-8e8f-003194ac726b.png)

**Comment by malavv** [comment]
Thanks for the update @shengjhen . That's a good point and there is an easy fix. I'm checking with others whether we need this behaviour or not before removing it. (It was made that way to allow both to be modified independently)

**Comment by shengjhen** [comment]
@malavv maybe can consider this image what i posted?

![image](https://user-images.githubusercontent.com/42288446/86932262-b7f26900-c16b-11ea-9332-e61c2ab2b5d0.png)
