### ISSUE TITLE
Game menu accessible from main menu after leaving game

### ISSUE THREAD

**Issue by mewmew** [OpenDiablo2/OpenDiablo2#523]
**Describe the bug**
The game menu is accessible from main menu (by pressing `[esc]`) after leaving a single game.

**To Reproduce**
On revision 9c2b1dccafbc89098edc5f7528875a595fccc9ad.

1. Start a new single player game.
2. Leave the game by opening the game menu and clicking "Save and exit game"
3. Now, from the main menu, press `[esc]`.
4. Game menu opens.

**Expected behavior**
Game menu only available from inside the game, now from main menu.

**Screenshots**
![screenshot_2020-07-02_22:24:21](https://user-images.githubusercontent.com/1414531/86406513-854ff880-bcb3-11ea-8688-86b64760e6b7.png)

**Comment by mewmew** [comment]
Wow, that was quick :tada:

**Comment by essial** [comment]
> Wow, that was quick 🎉

That's what she said.
