### ISSUE TITLE
Game crashes when entering from hero selection (new character) screen

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#528]
**Describe the bug**
Game crashes when you try to create a new character and enter game screen

**To Reproduce**
1. from main menu, click on single player
2. click create new character (if you have character saves already)
3. on hero selection screen, enter name and select hero
4. click ok button

**Expected behavior**
enter the game screen

**Screenshots**
![image](https://user-images.githubusercontent.com/936440/86437569-a287c580-bcb9-11ea-8844-2feab3ea77f8.png)

 - OS: Ubuntu 18.04.4 LTS

**Comment by essial** [comment]
Yup, term appears to be nil. I'll look at it now.
