### ISSUE TITLE
Write remaining d2datadict loaders

### ISSUE THREAD

**Issue by andrewDoing** [OpenDiablo2/OpenDiablo2#634]
**Problem**
Not all the *.txt files are loaded into the game from /data/global/excel

**Solution**
Write data loaders for the remaining .txt files

**Files remaining:**
patch_d2.mpq
- [x] books.txt
- [ ] compcode.txt (Hardcoded Reference File)
- [x] ElemTypes.txt
- [ ] events.txt (Hardcoded Reference File)
- [x] itemratio.txt
- [x] misscalc.txt
- [ ] monai.txt (Hardcoded Reference File)
- [x] monequip.txt
- [x] MonLvl.txt
- [x] MonMode.txt
- [ ] MonPlace.txt (Hardcoded Reference File)
- [x] MonPreset.txt (not sure, monpreset.txt exists somewhere)
- [x] MonProp.txt
- [x] monseq.txt
- [x] monsounds.txt
- [x] MonType.txt
- [x] monumod.txt
- [x] npc.txt
- [x] Overlay.txt
- [x] pettype.txt
- [x] PlrMode.txt
- [x] Runes.txt
- [x] shrines.txt
- [x] skillcalc.txt
- [x] soundenviron.txt
- [x] UniqueAppellation.txt
- ~~UniqueTitle.txt~~

d2exp.mpq
- ~~Aiparms.txt~~
- ~~Arena.txt~~
- [ ] ArmType.txt
- [x] AutoMap.txt
- ~~CharTemplate.txt~~
- [ ] Composit.txt
- [ ] HitClass.txt (Hardcoded Reference File)
- [x] LvlWarp.txt
- ~~MonItemPercent.txt~~
- ~~MonName.txt~~
- [x] ObjMode.txt (Hardcoded Reference File)
- [x] ObjType.txt
- [x] PlayerClass.txt
- [ ] PlrType.txt (Controls the animation used by characters
- [ ] RarePrefix.txt (in resource_paths.go, but doesn't have its own loader)
- [ ] RareSuffix.txt (in resource_paths.go, but doesn't have its own loader)
- [x] SoundEnviron.txt (lowercase named file in patch_d2.mpq, probably the same?)
- [x] Sounds.txt
- [ ] StorePage.txt (Hardcoded Reference File)
- [x] TreasureClass.txt
- [x] WeaponClass.txt
- [x] automagic.txt
- [ ] belts.txt
- [x] bodylocs.txt
- [ ] colors.txt (Hardcoded Reference File)
- [ ] cubemod.txt (Hardcoded Reference File)
- [ ] cubetype.txt (Hardcoded Reference File)
- [ ] gamble.txt (List of item codes that are available for gambling)
- [ ] hiredesc.txt (Hardcoded Reference File)
- [ ] lowqualityitems.txt (Hardcoded Reference File)
- [x] objgroup.txt
- [x] qualityitems.txt

~~d2data.mpq~~
All files in d2data are superseded by d2exp (no uniquely named txt files)

**Additional context**
MPQ precedence:
1. patch_d2.mpq
2. d2exp.mpq
3. d2data.mpq

This is a useful reference to the txt files: https://d2mods.info/forum/kb/index?c=4

**Comment by griffithsh** [comment]
This is a useful reference to the txt files: https://d2mods.info/forum/kb/index?c=4

**Comment by gravestench** [comment]
@Ziemas commented on #641 that unused txtfiles can be found here: https://d2mods.info/forum/viewtopic.php?t=34455

**Comment by gravestench** [comment]
Don't bother implementing loaders for the unused txt files. @andrewDoing can you remove the unused ones from this list?

**Comment by andrewDoing** [comment]
> Don't bother implementing loaders for the unused txt files. @andrewDoing can you remove the unused ones from this list?

Looks like UniqueTitle is the only file on the list that falls under unused.
