### ISSUE TITLE
Game crashes when "Save and Exit Game" is pressed

### ISSUE THREAD

**Issue by gurkankaymak** [OpenDiablo2/OpenDiablo2#707]
**Describe the bug**
Game crashes when "Save and Exit Game" is pressed on the escape menu

**To Reproduce**
1. Start a single player game
2. Press escape button
3. Select the "Save and Exit Game" option and press enter (or click the "Save and Exit Game" option)
4. Game crashes instead of returning to menu

**Expected behavior**
Game should not crash and return to the menu.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version: 10.15.6

**Comment by brendanporter** [comment]
Addressed with https://github.com/OpenDiablo2/OpenDiablo2/pull/713

**Comment by gurkankaymak** [comment]
closing the issue, since it's been fixed with #713
