### ISSUE TITLE
Any plans for an Android port?

### ISSUE THREAD

**Issue by Destroyer5150** [OpenDiablo2/OpenDiablo2#712]
Really just needs a button to switch from left click to right click and a few others to customize to your liking. Just make sure they're transparent and the game can be set to fit to screen. Would be nice to include the res mod and d2se for the medianxl mod and others. I'm currently using Exagear windows with the civ 3 controls if you ever wanna check it out.

**Comment by essial** [comment]
We cannot include mods as the mods are for the original D2 engine, and this is a total re-write. We would love to support android in the future, but is not in our v1.0 roadmap. Once we hit that point we absolutely will port to as many platforms as possible!
