### ISSUE TITLE
Crash at the very start

### ISSUE THREAD

**Issue by demoth** [OpenDiablo2/OpenDiablo2#734]
**Describe the bug**
After updating to `d0410001` the application no longer starts. Possibly case sensitivity issue:
**lstat /home/user/GameDev/Diablo2/Patch_D2.mpq: no such file or directory**
I have `patch_d2.mpq`.

**To Reproduce**
1. Checkout `d0410001`
2. go build; go run .
3. See error

**Expected behavior**
Application should start

**Desktop:**
 - OS: kubuntu 
 - Version 20.04

**Additional context**
output:
❯ go run .
main.go:26: OpenDiablo2 - Open source Diablo 2 engine
d2config.go:42: loading configuration file from /home/user/.config/OpenDiablo2/config.json...
lstat /home/user/GameDev/Diablo2/Patch_D2.mpq: no such file or directory
panic: runtime error: index out of range [36] with length 36

goroutine 1 [running, locked to thread]:
github.com/OpenDiablo2/OpenDiablo2/d2common/d2data/d2datadict.LoadLevelTypes(0xc00097e000, 0x298c, 0x3000)
        /home/user/GameDev/OpenDiablo2/d2common/d2data/d2datadict/level_types.go:59 +0x61b
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).loadDataDict(0xc0002000e0, 0x3fd3333333333333, 0x3ff0000000000000)
        /home/user/GameDev/OpenDiablo2/d2app/app.go:304 +0x53b
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).initialize(0xc0002000e0, 0x10, 0xc000143e78)
        /home/user/GameDev/OpenDiablo2/d2app/app.go:186 +0x5eb
github.com/OpenDiablo2/OpenDiablo2/d2app.(*App).Run(0xc0002000e0, 0x0, 0x0)
        /home/user/GameDev/OpenDiablo2/d2app/app.go:132 +0x279
main.main()
        /home/user/GameDev/OpenDiablo2/main.go:60 +0x316
exit status 2

**Comment by gravestench** [comment]
Edit your config file, the default assumes `Patch_D2.mpq`, and you have `patch_d2.mpq`

**Comment by demoth** [comment]
Ok it solved the problem. I was confused that the behavior changed very recently
