### ISSUE TITLE
When build: "multiple-value uuid.NewV4() in single-value context" on Arch Linux

### ISSUE THREAD

**Issue by gustavklopp** [OpenDiablo2/OpenDiablo2#745]
**Describe the bug**
Failure when building on Arch Linux

**To Reproduce**
1.  do `go get github.com/OpenDiablo2/OpenDiablo2`
2. See error
```
$ go get github.com/OpenDiablo2/OpenDiablo2
# github.com/OpenDiablo2/OpenDiablo2/d2networking/d2client/d2remoteclient
../go/src/github.com/OpenDiablo2/OpenDiablo2/d2networking/d2client/d2remoteclient/remote_client_connection.go:43:24: multiple-value uuid.NewV4() in single-value context
# github.com/OpenDiablo2/OpenDiablo2/d2core/d2map/d2mapentity
../go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2map/d2mapentity/factory.go:224:27: multiple-value uuid.NewV4() in single-value context
../go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2map/d2mapentity/map_entity.go:35:23: multiple-value uuid.NewV4() in single-value context

```
**Expected behavior**
it should build normally

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by gravestench** [comment]
What version of golang are you using?

**Comment by gustavklopp** [comment]
the one from the repo.
Apparently: 2:1.15.2-1 (Last Updated: 2020-09-09 21:19 UTC)
https://www.archlinux.org/packages/community/x86_64/go/

**Comment by gravestench** [comment]
Can I see your go.mod?

I can't reproduce this on my machine (running Lubuntu 18.04.4 LTS). 

Are you able to build if you make a new clone?

`uuid.NewV4` only returns a single value for me.
![image](https://user-images.githubusercontent.com/936440/93805790-08228880-fbfd-11ea-841b-79a2246ef467.png)

These are the contents of my go.mod
```golang
module github.com/OpenDiablo2/OpenDiablo2

go 1.14

require (
	github.com/JoshVarga/blast v0.0.0-20180421040937-681c804fb9f0
	github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751 // indirect
	github.com/alecthomas/units v0.0.0-20190924025748-f65c72e2690d // indirect
	github.com/go-restruct/restruct v0.0.0-20191227155143-5734170a48a1
	github.com/hajimehoshi/ebiten v1.11.4
	github.com/pkg/profile v1.5.0
	github.com/robertkrimen/otto v0.0.0-20191219234010-c382bd3c16ff
	github.com/satori/go.uuid v1.2.0
	github.com/stretchr/testify v1.4.0
	golang.org/x/image v0.0.0-20200618115811-c13761719519
	gopkg.in/alecthomas/kingpin.v2 v2.2.6
	gopkg.in/sourcemap.v1 v1.0.5 // indirect
)
```

**Comment by gravestench** [comment]
@gustavklopp can you try cloning my fork and building the `issue_745` branch?
https://github.com/gravestench/OpenDiablo2/tree/issue_745

**Comment by essial** [comment]
The only call I see takes in 0 parameters and returns a UUID and an error:
https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/generator.go#L68

**Comment by gravestench** [comment]
@essial see my screenshot above, golang reports that it only returns a uuid for the version that we were using (1.2). I think on the master branch of that repo it may be different.

**Comment by gustavklopp** [comment]
> contents of my go.mod

How can I display it (sorry I'm not used to Go)?

**Comment by gravestench** [comment]
@gustavklopp try to clone my fork and switch to the issue_745 branch and do a build

**Comment by gustavklopp** [comment]
O

> @gustavklopp try to clone my fork and switch to the issue_745 branch and do a build

Ok it's working now! Thanks a lot for your help!
