### ISSUE TITLE
Configure Controls Panel

### ISSUE THREAD

**Issue by leahiel** [OpenDiablo2/OpenDiablo2#753]
a.k.a hotkeys. This panel is found within Game Menu > Options > Configure Controls. It looks like this:
![image](https://user-images.githubusercontent.com/71794961/94301128-14c61a00-ff38-11ea-9eb0-c7c940e69a7b.png)

**Part One**: Visuals
Make the non-text visuals of the panel look correct. Also make sure the scroll bar works too, as it is a required feature of the menu. Currently this appears when you select the "Configure Controls" option:
![image](https://user-images.githubusercontent.com/71794961/94301595-d3823a00-ff38-11ea-9da4-e14bfca64bf6.png)

**Part Two**: Text
Note that nearly everything (if not everything) is present in the string table and should be pulled from there instead of hardcoded in, this will allow people to more easily translate different versions of the game. (Or even use different translations already present.)

**Part Three**: In-menu Functionality:
You should be able to change the hotkeys. Note that you can only have one button per action. E.g. if you try to assign /q/ to all the hotkeys, they get overwritten:
![image](https://user-images.githubusercontent.com/71794961/94301444-91f18f00-ff38-11ea-9c54-d18a87a0f5de.png)
Also, red text appears if there are no currently assigned hotkeys to that Function.

**Part Three point One**:
Defaulting should work and set the various Functions to the default Key mapping.

**Part Four**:
The hotkeys should work for the systems already programmed.  Assigning /q/ to inventory should allow the user to press /q/ to open the inventory.  This may require rewrite in other files.

**Comment by Ganitzsh** [comment]
I'm on it tw

**Comment by Ganitzsh** [comment]
@gravestench I believe we can close this one? maybe we should create a new one to handle the masking
