### ISSUE TITLE
(FreeBSD amd64) OpenDiablo2 can't find path to mpq files

### ISSUE THREAD

**Issue by nunotexbsd** [OpenDiablo2/OpenDiablo2#774]
Hello,

I've installed D2/LoD 1.14b with wine and renamed "Program Files" to "Program Files (x86)" to match config.json path.

It compiles and runs complaining about not finding mpq data files.

Here is a (small) log about "go run ." and full path to Diablo II folder:

https://termbin.com/wmf6

Thanks,

Nuno Teixeira

**Comment by gravestench** [comment]
check the capitalization of your mpq files against what is in your config file.

**Comment by gravestench** [comment]
the default `config.json` assumes `Patch_d2.mpq` instead of `patch_d2.mpq`

**Comment by essial** [comment]
`C:/Program Files (x86)/Diablo II/patch_d2.mpq` isn't a valid path in a unix/BSD environment. I'm guessing you need to change the path to something like `~/.wine/c/blablabla`.

**Comment by nunotexbsd** [comment]
config.json says "MpqPath": "C:/Program Files (x86)/Diablo II",

Should I change it to "real" unix path?

**Comment by gravestench** [comment]
yes

**Comment by essial** [comment]
OpenDiablo2 is running natively on your system so unless you're running it in windows, C:\ won't be a valid path.

**Comment by ThomasChr** [comment]
It nust be something like /home/username/.wine/drive_c/...

**Comment by nunotexbsd** [comment]
Yep! Those path with spaces was messing with engine.

I used a simple path and it found mpq files.

Before this issued be closed how do I log "go run ." to a file so I can sent to you for debug?

I only catched this from my screen:

https://termbin.com/9b7w3

**Comment by gravestench** [comment]
`go run . 2> log.txt`

**Comment by nunotexbsd** [comment]
2> or just > creates an empty file.

go run . | nc termbin.com 9999

gives same result :(

**Comment by essial** [comment]
GLX: Failed to create context: GLXBadFBConfig looks like you either don't have OpenGL support at all (doubtful), or the version of OpenGL it's trying to create isn't supported by your driver. What does glxinfo return?

**Comment by gravestench** [comment]
separate issue?

**Comment by essial** [comment]
Yeah it is, just make sure you include it in a new issue post.

**Comment by nunotexbsd** [comment]
Hope you right because this laptop is 10 years old:

https://termbin.com/gq2k

**Comment by gravestench** [comment]
@nunotexbsd make a separate issue for the gfx thing

**Comment by nunotexbsd** [comment]
I will do that but first I will try to know how to get a verbose compiling log from go and then I make a issue.

Thanks for you pacience :)

Nuno

**Comment by gravestench** [comment]
`go run . > log.txt 2>&1` should work

**Comment by nunotexbsd** [comment]
that gives "Ambiguous output redirect."

I also compiled main.go and executed ./main binary, it runs like "go run ." but I can't log it!

2>&1 gives empty log too

**Comment by gravestench** [comment]
This may depend on your environment (like the shell you're using), and I don't think this has anything to do with your original issue, or our project. If you need more help, please join our discord and we can assist you further.

**Comment by nunotexbsd** [comment]
I solved redirection imcompatabilities changing my csh shell to bash. I can log > 2> and 2>&1 now :)

I will make an issue in a moment.

Thanks!
