### ISSUE TITLE
VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by nunotexbsd** [OpenDiablo2/OpenDiablo2#775]
Hello,

I got this error when I run "go run .":

- [Error](https://termbin.com/eq9g)
- [glxinfo](https://termbin.com/n1yk)

OS: FreeBSD 12.2 RC1 amd64

**Comment by gravestench** [comment]
give detailed hardware specs

**Comment by gravestench** [comment]
`server glx version string: 1.4`

Your issue is probably similar to, if not exactly the same as, [this](https://github.com/vurtun/nuklear/issues/364). It's likely that you need better hardware. We dont have an explicit goal of making OD2 run on really old hardware.

**Comment by nunotexbsd** [comment]
Hardware specs:

- [official site](https://www.portatilmagalhaes.com/especificacoes-de-hardware-do-portatil-magalhaes/)
- [acpidump](https://termbin.com/dr95n8)
- [devinfo](https://termbin.com/bb8z)
- [dmesg](https://termbin.com/f73o)
- [pciconf](https://termbin.com/1oscx)
- [Xorg.0.log](https://termbin.com/xmlo)

**Comment by gravestench** [comment]
We use Ebiten as a rendering backend. Can you try to run one of the examples?

Can you try running the following:
```bash
go run -tags=example github.com/hajimehoshi/ebiten/examples/flappy
```

If your device cannot run the ebiten examples, then it is likely that your device doesnt support glfw3, which is what ebiten uses.

**Comment by essial** [comment]
OpenGL 1.4 is 18 years old and isn't going to be supported by anything modern. What you linked to claims to have 1GB of ram and a 900mhz celleron processor; this appears to be a laptop for young children (5 to 8 year olds) - and is basically an educational toy. At this point you can spend $35 and get a raspberry pi 4 which has double the ram and a quad core 1.4ghz processor. I'm sorry but there is absolutely no way we can support this spec.

**Comment by nunotexbsd** [comment]
Yep, it seems that this machine doesn't handle it. Soon I will be able to test it on newer pc.

Thanks!

https://termbin.com/ovkso
