### ISSUE TITLE
Need an abstraction between input events and game engine events

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#793]
Currently, all interaction in the game engine is hard-coded for specific input events (keyboard keys, mouse buttons).

However, we need some kind of abstraction between input events and the game events they are mapped to. 

We also need this mapping of input to game events to be configurable via the `config.json` file.

**Comment by gravestench** [comment]
This is blocking #794

**Comment by gravestench** [comment]
This is blocking #753

**Comment by Ganitzsh** [comment]
I'm on it
