### ISSUE TITLE
Help Screen Overlay: tooltips should show the actual keys which are bound to buttons/panels

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#794]
Depends on #793.

The hotkeys displayed in the help panel need to reflect the keys which are mapped to the game events displayed.

For example, if you were to change the hotkey for run/walk to `Spacebar` instead of `LeftControl`, it should be shown in the tooltip.

**Comment by gucio321** [comment]
It was solved in #972
