### ISSUE TITLE
Left/Right skill buttons need selected skills from character save file

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#799]
in `GameControls.Load`, the character save file data should be used to select the currently selected skills for left/right mouse buttons.

**Comment by gravestench** [comment]
I wonder if i can just assign @ThomasChr if i mention him in this issue...

**Comment by ThomasChr** [comment]
Now I‘m not doing it ;-)

**Comment by ThomasChr** [comment]
Can be closed!
