### ISSUE TITLE
Run/Walk toggle should change the button sprite

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#800]
When toggling run/walk, the button displayed near the stamina bar should reflect the current toggle state.

**Comment by ThomasChr** [comment]
I thought this works. I‘ll take a look!
PS: I also tackle the stamina bar getting red near the end with that, ok?

**Comment by gravestench** [comment]
There was a TODO comment, i'm removing those comments and making issues for them. Perhaps it works already. Please close if it is already working.

**Comment by ThomasChr** [comment]
Great. I‘ll check it then!

**Comment by ThomasChr** [comment]
Changing the sprite works a treat. Issue can be closed!

**Comment by gravestench** [comment]
when disabled, the sprite is missing:
![image](https://user-images.githubusercontent.com/936440/97114686-30475080-16af-11eb-8548-6ab9fbb47b9d.png)

**Comment by Ganitzsh** [comment]
I'll look into it

**Comment by gravestench** [comment]
Fixed by #816
