### ISSUE TITLE
Add Quest Log ui panel

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#801]
This issue does not pertain to any of the quest state logic.

the dc6 resources are located in `data/global/ui/menu/`. These need to be added to `d2common/d2resource/resource_paths.go` and the quest panel should be added in `d2game/d2player/`.

**Comment by gucio321** [comment]
I'm working on it.

**Comment by gravestench** [comment]
resolved by #956 and #957
