### ISSUE TITLE
Replace static health/mana/experience values with values from character save file

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#815]
in `d2core/d2hero/hero_stats_state.go`

There are currently static test values that set the current helth, mana, and experience. These need to be removed and populated with values from the character save file.

**Comment by Ganitzsh** [comment]
Is the Level also missing?

**Comment by gravestench** [comment]
I think so, yes

**Comment by ThomasChr** [comment]
I think this one can be close after the PR from @stephenhoran

**Comment by gravestench** [comment]
resolved by #886
