### ISSUE TITLE
Headless/Dedicated Server

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#827]
The game server should be capable of being launched without a renderer, input manager, or audio engine.

**Comment by Zaprit** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vehicula nisl dolor, sit amet euismod nibh luctus eget. Phasellus pretium condimentum varius. Nulla condimentum, velit quis interdum tincidunt, lectus dui ultricies ante, non egestas nulla lectus vitae tellus. Cras quis eros metus. Quisque vel ipsum vitae dolor tincidunt congue auctor id massa. Aliquam tristique erat at sem maximus, vel feugiat tellus tristique. Duis sed nisl in ipsum sagittis tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis hendrerit fermentum arcu. Etiam a venenatis velit.
