### ISSUE TITLE
Migrate to Ebiten v2.0 API

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#859]
We need to update to using ebiten v2.0 API. The v2.0 api is not compatible with what we have been using (v1.12), so may require significant effort.

**Comment by essial** [comment]
Please refer to the [migration guide](https://ebiten.org/documents/to_v2.html). Pay careful attention to it, as some fundamental things have changed, such as streams no longer getting closed by Ebiten (thus we need to close them ourselves).
