### ISSUE TITLE
Save current health, mana, level, and experience to the character save file.

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#865]
blocking #815

**Comment by Ganitzsh** [comment]
Wasn't it done with I guess this one is done?

**Comment by ThomasChr** [comment]
No, it‘s only loaded. Not saved. But I think @stephenhoran is working on the saving...

**Comment by stephenhoran** [comment]
Correct this is not resolved yet... have something in the works today look out for a PR @ThomasChr.

**Comment by Ganitzsh** [comment]
Okay my bad, I thought it was because it was added to the HeroState and therefore handled in the SavePlayer packet

**Comment by gravestench** [comment]
Any update on this issue? @stephenhoran

**Comment by ThomasChr** [comment]
@stephenhoran If you can't find any time to tackle this, I would do it. If thats okay for you?

**Comment by gravestench** [comment]
@ThomasChr I'll just assign it to you

**Comment by ThomasChr** [comment]
Finally my lonely days of watching netflix in my scarse spare time are over. I'm so glad!
