### ISSUE TITLE
Save currently selected skills in character save file

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#868]
The skills (or skill indices, whatever) that are assigned to left/right mouse buttons need to be saved to the character save file.

There are 2 sets of left/right indices that need to be saved, one for main and another for secondary weapon+shield equipment slots.

currently blocking #799

**Comment by ThomasChr** [comment]
@gravestench Assign me both Issues please!

**Comment by ThomasChr** [comment]
Closely related to #867
