### ISSUE TITLE
Display error with server is full

### ISSUE THREAD

**Issue by stephenhoran** [OpenDiablo2/OpenDiablo2#884]
Display message when a ServerFull packet is received from the server.

**Comment by gravestench** [comment]
I think this is a duplicate of #805

**Comment by stephenhoran** [comment]
Maybe close... one being unable to connect... the other being if the Server is full... which the client will receive a packet for.

**Comment by gravestench** [comment]
not to split hairs, but the server being full would be one of many reasons why a client couldn't connect.

I'll leave this issue open.

**Comment by stephenhoran** [comment]
Fair point... We can link it to 805 then and close this... might just need to update the comment is all so we don't miss this.

**Comment by stephenhoran** [comment]
Duplicate of #805
