### ISSUE TITLE
Is it possible to port it under MAC ?

### ISSUE THREAD

**Issue by krolhm** [OpenDiablo2/OpenDiablo2#913]
I know that there are not many mac players but...
I would like to know if there was a possibility to adapt your version for mac?

**Comment by ThomasChr** [comment]
Many of our coders use Mac. So yes, it‘s absolutely possible and if you dare to compile yourself you can try it right now.
In the future there will be a signed version for mac!

**Comment by gravestench** [comment]
It already compiles for MacOS :+1: 

Apple's decision to drop 32-bit support is one of the reasons for the project. You can still buy D2 from blizzard, but you can't install it on MacOS Catalina (iirc...) onwards

**Comment by essial** [comment]
I'm the org admin and I work exclusively on Macs. Technically this project was ported FROM the Mac to other platforms!

**Comment by krolhm** [comment]
But how to do it ? I'm on mac and when I run the .sh it gives me this ...

`➜  OpenDiablo2-master ./build.sh 
OpenDiablo 2 Build Script 0.0.8
cat: /etc/*release: No such file or directory
./build.sh: line 17: pacman: command not found
Check Go
Install Go for OpenDiablo 2 ()? y/n
y
Install libraries
./build.sh: line 109: /Users/rapha/.config/OpenDiablo2/.libs: No such file or directory
Mac OS detected, no dependency installation necessary...
Build OpenDiablo 2
./build.sh: line 113: go: command not found
./build.sh: line 114: go: command not found
Build finished. Running OpenDiablo2 will generate a config.json file.
If there are subsequent errors, please inspect and edit the config.json file. See doc/index.html for more details
`

**Comment by essial** [comment]
Open the command prompt and go to the folder the source is in, and run:
`go get .`

Then to run it:
`go run .`

**Comment by krolhm** [comment]
Hello when I do the go run. I get this error message but I don't have a diablo II application in applications/ so what should I do?
```main.go:19: OpenDiablo2 - Open source Diablo 2 engine
[File Loader][INFO] adding filesystem source `/var/folders/4t/3gp5z2yd067_w_jm0fcg7f900000gn/T/go-build218027145/b001/exe`
[File Loader][INFO] adding filesystem source `/Users/rapha/Library/Application Support/OpenDiablo2`
[File Loader][INFO] from /Users/rapha/Library/Application Support/OpenDiablo2, loading config.json
[File Loader][ERROR] lstat /Applications/Diablo II/Diablo II Patch: no such file or directory

**Comment by essial** [comment]
When you run, you should see an error screen of where your config.json file goes. You're going to have to point it to your diablo 2 files. By default on Mac it looks at where D2 gets installed on Mac if you installed the official Mac version. Of course for most of us (myself included), you can't even run the installer on Mac any more, so an adjustment needs to be made.

The config file should be located at:
`/Users/[your user name]/Library/Application Support/OpenDiablo2/config.json`

I installed D2/LOD and patch using Parallels desktop and copied it over to `~/Documents/D2`, but you could also install it on a VM or windows machine and copy the files over. Here is my config.json values:

```
{
  "MpqLoadOrder": [
	"Patch_D2.mpq",
	"d2exp.mpq",
	"d2xmusic.mpq",
	"d2xtalk.mpq",
	"d2xvideo.mpq",
	"d2data.mpq",
	"d2char.mpq",
	"d2music.mpq",
	"d2sfx.mpq",
	"d2video.mpq",
	"d2speech.mpq"
  ],
  "Language": "ENG",
  "MpqPath": "/Users/lunaticedit/Documents/D2/",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten"
}
```

**Comment by krolhm** [comment]
I have all this, how do I know which file goes with what ???

```
1.07/                                              18-May-2016 16:40                   -
1.09d/                                             18-May-2016 16:40                   -
1.10/                                              18-May-2016 16:40                   -
1.11b/                                             25-Mar-2017 12:32                   -
1.12a/                                             25-Mar-2017 12:40                   -
1.13c/                                             25-Mar-2017 11:23                   -
1.13c_m/                                           18-May-2016 16:40                   -
1.13d/                                             25-Mar-2017 11:34                   -
1.14a/                                             25-Mar-2017 12:34                   -
1.14b/                                             25-Mar-2017 12:35                   -
1.14c/                                             25-Mar-2017 12:35                   -
1.14d/                                             25-Mar-2017 12:36                   -
D2.LNG                                             18-May-2016 13:24                1536
Diablo II.exe                                      18-May-2016 13:24               36864
License.txt                                        18-May-2016 13:24               14144
SmackW32.dll                                       18-May-2016 13:24               95232
binkw32.dll                                        18-May-2016 16:39              263168
d2char.mpq                                         18-May-2016 16:36           266930529
d2data.mpq                                         18-May-2016 16:38           256225123
d2exp.mpq                                          18-May-2016 16:38           250156780
d2music.mpq                                        18-May-2016 16:38           345349632
d2readme.htm                                       18-May-2016 13:24               75921
d2sfx.mpq                                          18-May-2016 16:38            51913383
d2speech.mpq                                       18-May-2016 16:36           517564556
d2video.mpq                                        18-May-2016 16:37           424619671
d2xtalk.mpq                                        18-May-2016 16:20            60278192
d2xvideo.mpq                                       18-May-2016 16:35           110685575
ijl11.dll                                          18-May-2016 13:24              180224
md5.txt                                            25-Mar-2017 12:41               10847
xreadme.htm                                        18-May-2016 13:24               95714

**Comment by krolhm** [comment]
I have all this, how do I know which file goes with what ???*
sorry I forgot to translate

**Comment by gucio321** [comment]
so,
you for example have OpenDiablo2 binary in /Users/username/od2
create ne wolder e.g. /Users/username/od2/mpq and copy following files into it:
d2char.mpq, d2data.mpq, d2exp.mpq, d2music.mpq, d2sfx.mpq, d2speach.mpq, d2video.mpq, d2xtalk.mpq, d2xvideo.mpq.
You need to have patch_d2.mpq for 1.14d version (you can google for it)
after that, edit your config.json file ( /Users/username/Library/Application Support/OpenDiablo2/config.json):
`{
  "MpqLoadOrder": [
	"Patch_D2.mpq",
	"d2exp.mpq",
	"d2xmusic.mpq",
	"d2xtalk.mpq",
	"d2xvideo.mpq",
	"d2data.mpq",
	"d2char.mpq",
	"d2music.mpq",
	"d2sfx.mpq",
	"d2video.mpq",
	"d2speech.mpq"
  ],
  "Language": "ENG",
  "MpqPath": "/Users/username/od2/mpq/",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten"
}`

**Comment by krolhm** [comment]
Thank you all I'm getting there a bit but I still have some gray areas ....

Here are my game files
```
1.07/                                              18-May-2016 16:40                   -
1.09d/                                             18-May-2016 16:40                   -
1.10/                                              18-May-2016 16:40                   -
1.11b/                                             25-Mar-2017 12:32                   -
1.12a/                                             25-Mar-2017 12:40                   -
1.13c/                                             25-Mar-2017 11:23                   -
1.13c_m/                                           18-May-2016 16:40                   -
1.13d/                                             25-Mar-2017 11:34                   -
1.14a/                                             25-Mar-2017 12:34                   -
1.14b/                                             25-Mar-2017 12:35                   -
1.14c/                                             25-Mar-2017 12:35                   -
1.14d/                                             25-Mar-2017 12:36                   -
D2.LNG                                             18-May-2016 13:24                1536
Diablo II.exe                                      18-May-2016 13:24               36864
License.txt                                        18-May-2016 13:24               14144
SmackW32.dll                                       18-May-2016 13:24               95232
binkw32.dll                                        18-May-2016 16:39              263168
d2char.mpq                                         18-May-2016 16:36           266930529
d2data.mpq                                         18-May-2016 16:38           256225123
d2exp.mpq                                          18-May-2016 16:38           250156780
d2music.mpq                                        18-May-2016 16:38           345349632
d2readme.htm                                       18-May-2016 13:24               75921
d2sfx.mpq                                          18-May-2016 16:38            51913383
d2speech.mpq                                       18-May-2016 16:36           517564556
d2video.mpq                                        18-May-2016 16:37           424619671
d2xtalk.mpq                                        18-May-2016 16:20            60278192
d2xvideo.mpq                                       18-May-2016 16:35           110685575
ijl11.dll                                          18-May-2016 13:24              180224
md5.txt                                            25-Mar-2017 12:41               10847
xreadme.htm                                        18-May-2016 13:24               95714
```


With that I was able to put this but I can't find a Diablo II Expansion .mpq

And one more thing, in each subfolder I have a Patch_D2.mpq so I don't know which one to choose ...

```
{
  "MpqLoadOrder": [
    "Patch_D2.mpq",
    "d2exp.mpq",
    "Diablo II Expansion Movies",
    "Diablo II Expansion Music",
    "Diablo II Expansion Speech",
    "d2data.mpq",
    "d2char.mpq",
    "d2music.mpq",
    "d2sfx.mpq",
    "d2video.mpq",
    "d2speech.mpq"
  ],
  "Language": "ENG",
  "MpqPath": "/Users/rapha/Documents/D2/",
  "TicksPerSecond": -1,
  "FpsCap": 0,
  "SfxVolume": 1,
  "BgmVolume": 0.3,
  "FullScreen": false,
  "RunInBackground": true,
  "VsyncEnabled": true,
  "Backend": "Ebiten",
  "LogLevel": 3
}

**Comment by essial** [comment]
Use the files I have in my example config file. Those are the windows file names, you're trying to look for the Mac file names but are using the windows versions of the filenames.

**Comment by krolhm** [comment]
ok thank you I did that but I have a red screen with this message ...
`record on line 721: wrong number of fields

**Comment by gravestench** [comment]
@krolhm Some of the txt files have different (incompatible) schemas between some versions of d2. Also, the order in which you have placed your `mpq` files matters, as that is the order in which the mpq's are processed. You have a peculiar setup, as you seem to have many d2 versions. The way your directory is organized is not standard at all.

One way to solve your problem is to simply create a new directory, and successively copy all of the MPQ's into this new directory, starting with the oldest version to the newest version. Do not use the MPQ files directly inside of `/Users/rapha/Documents/D2/`. I don't know what version of MPQ's those are and i don't think there is an easy way to check....
