### ISSUE TITLE
Add support for non-english locales

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#924]
related to #863 

Currently, using a non-english locale will cause a crash.

We need to use the locale from the mpq to load specific string tables and fonts. See #863 for where the local is stored. exactly which sting tables and fonts get loaded needs to be determined.

**Comment by gucio321** [comment]
I think, it can be closed now.

**Comment by gravestench** [comment]
resolved by #927, #929, #931
