### ISSUE TITLE
NPC hover-label is displayed above UI panels (eg. inventory)

### ISSUE THREAD

**Issue by gucio321** [OpenDiablo2/OpenDiablo2#936]
**Describe the bug**
 If NPC walks under the inventory window, we still can see his label

**To Reproduce**
1. Go to inventory window
2. If your mouse will be over the NPC, which walks under the menu, you can see its label

**Additional context**
That's minor bug

**Comment by ThomasChr** [comment]
This problem only existed for the inventory panel. Skilltree, questlog and heroStats Panel are rendered differently and don't have this problem.
