### ISSUE TITLE
Minibar does not open if another window is open

### ISSUE THREAD

**Issue by ThomasChr** [OpenDiablo2/OpenDiablo2#949]
**Describe the bug**
minibar does not open anymore if inventory or skill tree is open

**To Reproduce**
Open the skill tree and try to open the minibar at the bottom. It won't open.

**Expected behavior**
it should open

**Comment by gucio321** [comment]
Yah, it is expected:
```        if !m.movedLeft && !m.movedRight {
                m.panelGroup.SetVisible(true)
        }
```

**Comment by gucio321** [comment]
ok, fixed in #953
