### ISSUE TITLE
Free assets version

### ISSUE THREAD

**Issue by erlend-sh** [OpenDiablo2/OpenDiablo2#959]
> The engine is configured via the config.json file. By default, the configuration assumes that you have installed Diablo 2 and the expansion via the official Blizzard Diablo2 installers using the default file paths.

I’d really love to play the game on “free-assets” rather than “diablo2-assets” mode, maybe even by default. I bought the game way back (and loved it), but I’ve since lost the CDs and keys.

My main curiosity for OpenDiablo2 is to see if it _handles_ the same as Diablo 2. I’m interested in OD2 for its future modding capabilities so I can make my own Diablo-like spinoff with it. It’s awesome that the classic D2 assets can be loaded, they’re just not necessary for my use case.

I’d be happy to help scavenge for Good Enough resources for the most essential assets to begin with, but I’d need a better understanding of what the asset specs are.

**Comment by gravestench** [comment]
look at `d2common/d2resource/resource_paths.go` for a list of the resources we currently load.

look in `d2core/d2records/` for the record structs, these come frome tsv files inside of the mpq's (mostly from `data/global/excel/`)

What you're wanting is a full mod of the game that shares no assets with retail, only the engine. is this correct?

**Comment by gravestench** [comment]
As much as i like the thought of a "free assets" version of the game, the amount of work required to achieve this goal would be astronomical. Perhaps we can work towards this at some other time, but we have not yet implemented the engine and are still quite far away from a playable release.

**Comment by erlend-sh** [comment]
Thanks! Will check Discord etc.

Fine to close, but I’ll still point out that the point here wouldn’t be to have a freely licensed copy of 100% of the Diablo 2 assets, but rather <1%, starting with whatever is readily available.

One such place to start would be:
https://pvgames.itch.io/infernus-tileset
https://pvgames.itch.io/pvgames-free-assets-christmas-krampus

**Comment by gravestench** [comment]
oof, the camera angle in those tilesets are _quite severe_.
